master:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true -Dorg.jenkinsci.plugins.gitclient.Git.timeOut=11 -Duser.timezone=America/Denver -XX:+UseConcMarkSweepGC"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - /var/jenkins_home
